services:
  db:
    image: postgres:16
    container_name: etsy_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: etsyadmin
      POSTGRES_DB: etsy_analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: